############# English navigation ##############

# main menu
[[main]]
name = "Trang chủ"
url = ""
weight = 1

[[main]]
name = "Về chúng tôi"
url = "about/"
weight = 2

[[main]]
name = "sản phẩm"
url = "san-pham/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4
  
[[main]]
name = "Liên hệ"
url = "contact/"
weight = 5


# footer menu
[[footer]]
name = "Về chúng tôi"
url = "about/"
weight = 2

[[footer]]
name = "Sản phẩm"
url = "san-pham/"
weight = 3

[[footer]]
name = "Blog"
url = "blog/"
weight = 4

[[footer]]
name = "Liên hệ"
url = "contact/"
weight = 5
